---
title: "Heatwaves Data Analysis"
author: "Tithra CHAP"
date: "2020"
output: html_document
---

QUESTION 1:

```{r setup, include=FALSE}
#Need to install "rnoaa" package
library(rnoaa)
library(tidyverse)
library(lubridate)

options(noaakey = "hlFFAZquLPnvTlhSvAcaYrivMLRbjYBO")

#Retrive dataset from NOAA, But retrival only limited by 1000 records. 
#Therefore we need to download 2 times
#The station name is Perth Airport
tmp1 <- ncdc(datasetid = 'GHCND', stationid = 'GHCND:ASN00009021',
            startdate = '2013-07-01', enddate = '2014-06-30',limit=1000)
tmp2 <- ncdc(datasetid = 'GHCND', stationid = 'GHCND:ASN00009021',
            startdate = '2014-03-08', enddate = '2014-06-30',limit=1000)

#Combine them together
tmp <- rbind(tmp1$data,tmp2$data)

#Remove unnecessary collumns & format the data
perth_temp <- tmp[,-(5:8)]
perth_temp <-perth_temp %>%
            mutate(value = value/10,
                   date = as.Date(date),
                   station = NULL)

#Spread the respective values to the appropriate columns
perth_temp <- perth_temp %>%
  spread(datatype,value)

#Display columns, rows, and period coverage in the dataset
#Need to install (skimr) package
library(skimr)
skim(perth_temp)
```
QUESTION 2: All descriptions are in the report.

QUESTION 3:
```{r warning=FALSE , message=FALSE}
#Question 3.1: Royal Perth Hospital is selected for modeling.
#==================================================================
#Step 1/2: get the dataset and clean it up
#This procedure was done in Assignment 1
library(anytime) #need install "anytime" package for converting Date data below

ed_data_link <- "govhack3.csv"
top_row <- read_csv(ed_data_link, col_names = FALSE, n_max = 1)
second_row <- read_csv(ed_data_link, n_max = 1)

column_names <- second_row %>%
  unlist(., use.names=FALSE) %>%
  make.unique(., sep = "__") # double underscore

column_names[2:8] <- str_c(column_names[2:8], '0', sep='__')
myData <- read_csv(ed_data_link, skip = 2, col_names = column_names)
facility <- top_row[!is.na(top_row)]
myData <- myData %>%
  gather(key="index",value="values",-Date)
myData <- myData %>%
  separate(col = index,
           into = c("attributes","facility_id"), 
           sep = "__")
myData$facility_id <- as.integer(myData$facility_id)
myData$facility_id <- myData$facility_id + 1
myData <- myData %>%
  mutate(Facility_name = facility[facility_id],facility_id=NULL)
myData <- myData %>%
  spread(attributes,values)
for (i in myData[,1])
  x <- str_split(i,pattern = fixed("-"),simplify = T)
myData$Date <- str_c("20",x[,3],x[,2],x[,1])
myData$Date <- anydate(myData$Date)
myData[,-(1:2)] <- sapply(myData[,-(1:2)],as.integer)
myData[is.na(myData)] <- 0
cat(c("Royal Perth Hostpital is selected for the model!!!\nThe detail is down below:\n============================\n"))

#Step 2/2: selecting "Royal Perth Hospital" into [Hospital] dataset
Hospital <- subset(myData, Facility_name == "Royal Perth Hospital")
Hospital <- Hospital[order(Hospital$Date),] #Sort Hospital data by date

#Qestion 3.2: Predict Y using predictor variable 'date'
#==================================================================
library(broom)
lin_model <- lm(Admissions ~ Date, data = Hospital)
results <- lin_model %>% augment

#Qestion 3.2: Plot the fitted value and the residuals
results %>% 
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_point() + 
  geom_smooth(colour = 'blue') 

results %>% 
  ggplot(aes(sample = .std.resid)) +
  geom_qq() + 
  geom_qq_line(col = 'blue')

#Access the model fit 
lin_model %>% tidy 
lin_model %>% glance

#Question 3.3: Fit using generalize adaptive model
#Here poision model is used we measure the count of respond variable
#==================================================================
library(mgcv)
Hospital_adj <- Hospital %>% 
  mutate(date_index = as.numeric(Date))#Add date_index column

#fit the model
gam_model_1 <- gam(Admissions ~ s(date_index),
               family=poisson(link=log), data=Hospital_adj)

summary(gam_model_1)
gam.check(gam_model_1)

```

```{r}
#Question 3.4: Incorporate the previous model with weekly seansonality
#==================================================================
# Add date_index and wday(day of the week) into dataset
Hospital_adj <- Hospital %>% 
  mutate(date_index = as.numeric(Date),
         wkday = factor(wday(Date, label = TRUE), ordered = FALSE )) 

#fit the new model (model_2)
gam_model_2 <- gam(Admissions ~ s(date_index, by = wkday) + wkday,
               family=poisson(link=log), data=Hospital_adj)

AIC(gam_model_1, gam_model_2)
summary(gam_model_2)
gam.check(gam_model_2)

```
```{r}
#Question 3.5: 6.	Is your day-of-the-week variable numeric, ordinal, or categorical? Does the decision affect the model fit?
#==================================================================
#Testing wday with numerical value
Hospital_adj <- Hospital %>% 
  mutate(date_index = as.numeric(Date),
         wkday = factor(wday(Date, label = FALSE), ordered = FALSE ))

gam_model_3 <- gam(Admissions ~ s(date_index, by = wkday) + wkday,
              family=poisson(link=log), data=Hospital_adj)
#=================================================================
#Testing wday with ordinal value
Hospital_adj <- Hospital %>% 
  mutate(date_index = as.numeric(Date),
         wkday = factor(wday(Date, label = TRUE), ordered = TRUE ))

gam_model_4 <- gam(Admissions ~ s(date_index, by = wkday) + wkday,
              family=poisson(link=log), data=Hospital_adj)

#Compare using AIC measurement
AIC(gam_model_2, gam_model_3, gam_model_4)
```
QUESTION 4:

```{r}
# Task 4.1.2: Use the NOAA data to calculate the daily EHF values for the Perth area during the relevant time period. Plot the daily EHF values.
#=====================================================================================
#Calculate the T95 percentile
climate <- perth_temp
T95 <- mean(climate$TMAX) * 95/100

#Find daily three-days-period of TDP3
library(RcppRoll) # need to install RcppRoll package
climate <- climate %>%  mutate(TDP3 = roll_meanr(lag(TMAX), 3))

#Find Excessive Heat Indice of Significant Index (EHI_sig)
climate <- climate %>%  mutate(EHI_sig = TDP3 - T95)

#Find Excessive Heat Indice of Acclimatisation Index (EHI_accl)
climate <- climate %>%  
  mutate(TDP30 = roll_meanr(lag(TMAX), 30),
         EHI_accl = TDP3 - TDP30)

#Find the Excessive Heat Factor (EHF)
climate <- climate %>%  
  mutate(EHF = ifelse(EHI_sig>0, EHI_sig,0)*ifelse(EHI_accl>1,EHI_accl,1))

climate %>%
  ggplot(aes(x = date, y = EHF)) + 
  geom_line() + 
  labs(y="Excessive Heat Factor indices", x = "Period") +
  ggtitle("Excessive Heat Factor by month")
climate

```

```{r}
# 4.2: Use the EHF as an additional predictor to augment the model(s) that you fitted before. Report the estimated effect of the EHF on the ED demand. Does the extra predictor improve the model fit? What conclusions can you draw?
#===================================================================================

#Link the weather data (EHF) with Hospital data
Hospital_adj <- Hospital_adj %>% left_join(select(climate, Date = date, EHF))

#fit the new model by adding EHF (model_5)
gam_model_5 <- gam(Admissions ~ s(date_index, by = wkday) + wkday + s(EHF),
              family=poisson(link=log), data=Hospital_adj)

AIC(gam_model_2, gam_model_5)
summary(gam_model_5)
gam.check(gam_model_5)

```
```{r}
# 4.3: Can you think of extra weather features that may be more predictive of ED demands? Try incorporating your feature into the model and see if it improves the model fit.
#===================================================================================

#Link the weather data (EHF) with Hospital data
Hospital_adj <- Hospital_adj %>% left_join(select(climate, Date = date, PRCP))

#fit the new model by adding EHF (model_5)
gam_model_6 <- gam_model_5 %>% update(.~. + s(PRCP))

AIC(gam_model_5, gam_model_6)
summary(gam_model_6)
gam.check(gam_model_6)
```

QUESTION 5: The description is only in the report 